### ISSUE TITLE
Meta: Prep and make this repo public

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-docker-extensibility#53]
Do the prep work needed to make this repo public

- [x] #48
- [x] Verify credscan/policheck/etc.
- [x] Enforce all branch protection rules
- [x] [OSS approval](https://dev.azure.com/ossmsft/Reviews/_workitems/edit/43475)
- [ ] https://github.com/microsoft/vscode-docker/pull/3982
- [x] Final reviews
